### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [LoveDuckie/dissertation-ms-pacman-ai#1]
Hello, under what license is this project released under ? I would like to study it to learn from it. Thank you.

**Comment by LoveDuckie** [comment]
Hi @suprafun 

There's currently no license for it, but I give it one if you would like to learn from it. The only thing I ask is that you don't use it for commercial purposes.

**Comment by LoveDuckie** [comment]
![image](https://user-images.githubusercontent.com/692378/84565317-2b1ce100-ad60-11ea-9e1a-4305561ebb5d.png)

Done.

Thanks for creating this issue.
